# numpy

In [1]:
# import numpy library
import numpy as np

In [2]:
lst = [1,2,3,4]
np.array(lst) # np as alias for numpy

array([1, 2, 3, 4])

In [3]:
# single dimensional array as output 

In [5]:
lst = [1,2,3,4]
arr=np.array(lst) 

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.shape  # only one value

(4,)

In [9]:
lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [3,4,5,6,7]

np.array([lst1,lst2,lst3])  # multi deimensional array

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [13]:
lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [3,4,5,6,7]

arr1=np.array([lst1,lst2,lst3])  # multi deimensional array

In [14]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [15]:
type(arr1)

numpy.ndarray

In [17]:
arr1.shape   # 3 row 5 column

(3, 5)

In [18]:
# indexing
arr[3]

4

In [19]:
arr

array([1, 2, 3, 4])

In [20]:
arr[3]=5 # we can change 

In [21]:
arr

array([1, 2, 3, 5])

In [22]:
arr[1:3]

array([2, 3])

In [23]:
arr[1:]

array([2, 3, 5])

In [24]:
arr[:-1]

array([1, 2, 3])

In [25]:
arr[::]

array([1, 2, 3, 5])

In [26]:
arr[::-1]

array([5, 3, 2, 1])

In [27]:
arr[::-2]

array([5, 2])

In [28]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [29]:
arr1[:,1] # first col data first se 2 second se 3 and third se a4 ka 1 index wala 2,3,4 

array([2, 3, 4])

In [30]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [31]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])